version: '3.7'

services:
  nginx:
    build:
      context: docker/local
      dockerfile: nginx.dockerfile
    ports:
      - '${APP_PORT:-80}:80'
    volumes:
      - .:/app
    networks:
      - internal
    depends_on:
      - mysql

  php-cli:
    build:
      context: docker/local
      dockerfile: php-cli.dockerfile
    container_name: php-cli
    volumes:
      - ./:/app
    depends_on:
      - mysql
    networks:
      - internal

  php-fpm:
    build:
      context: docker/local
      dockerfile: php-fpm.dockerfile
    container_name: php-fpm
    environment:
      XDEBUG_CONFIG: "client_host=host.docker.internal remote_enable=1 mode=debug"
      XDEBUG_SESSION: PHPSTORM
      XDEBUG_MODE: "debug"
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - ./:/app
    depends_on:
      - mysql
    networks:
      - internal

  mysql:
    image: 'mysql:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - database:/var/lib/mysql
    networks:
      - internal
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]

  redis:
    image: redis:latest
    ports:
      - "63790:6379"
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  database:
